### ISSUE TITLE
ImportError: cannot import name 'ddf_mul_ext'

### ISSUE THREAD

**Issue by jia-604** [theFoxofSky/ddfnet#28]
Hello，I met this question，can you help me?

 python grad_check.py
Traceback (most recent call last):
  File "grad_check.py", line 8, in <module>
    from ddf import ddf
  File "/media/omnisky/34B22D6336AC1687/JSS/ddfnet-main/ddf/__init__.py", line 1, in <module>
    from .ddf import *
  File "/media/omnisky/34B22D6336AC1687/JSS/ddfnet-main/ddf/ddf.py", line 17, in <module>
    from .ddf import ddf_mul_ext, ddf_mul_faster_ext, ddf_add_ext, ddf_add_faster_ext
ImportError: cannot import name 'ddf_mul_ext'

**Comment by theFoxofSky** [comment]
It seems like you have not setup the ddf an move the *.so files to the ddf folder

**Comment by theFoxofSky** [comment]
It seems that you have not set up the ddf and moved the *.so files to the ddf folder.

**Comment by foxquan** [comment]
> It seems that you have not set up the ddf and moved the *.so files to the ddf folder.

Hello，I have run the grad_check.py sucessfully .but when I debug this code ，I met similar question.Can you help me?
ImportError: cannot import name 'ddf_mul_ext' from 'ddf_model.build' (unknown location)

**Comment by theFoxofSky** [comment]
Please moved the *.so files to the ddf folder instead of ddf.build folder
