### ISSUE TITLE
Error about grad_check.py

### ISSUE THREAD

**Issue by xiaoachen98** [theFoxofSky/ddfnet#32]
Thanks for your excellent work!
I have already installed the ddf pkg with python==3.8, cuda=11.1.
And when I run the grad_check.py, the error accured as:
Traceback (most recent call last):
  File "grad_check.py", line 40, in <module>
    out_ddf_o = ddf(feat, channel_att, spatial_att, 3, 2, 1, 'mul', 'o')
  File "/mnt/lustre/chenlin.vendor/code/mmclassification/mmcls/models/utils/ddf/ddf.py", line 86, in forward
    OP_DICT[op_type].forward(features, channel_filter, spatial_filter,
RuntimeError: ddf operation is not compiled with GPU support

What should I do to solve this error?

**Comment by xiaoachen98** [comment]
It's because I want to cite your paper and re-implement it in mmclassification, waiting for your response.
