### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by singularity97** [theFoxofSky/ddfnet#9]
Hi,there's an error when I run the code 

`Traceback (most recent call last):
  File "grad_check.py", line 8, in <module>
    from ddf import ddf
  File "/home/notebook/code/ddfnet/ddf/__init__.py", line 1, in <module>
    from . import ddf
  File "/home/notebook/code/ddfnet/ddf/ddf.py", line 19, in <module>
    from . import ddf_mul_ext, ddf_mul_faster_ext, ddf_add_ext, ddf_add_faster_ext
ImportError: cannot import name 'ddf_mul_ext' from partially initialized module 'ddf' (most likely due to a circular import) (/home/notebook/code/ddfnet/ddf/__init__.py)` 

I don't know whether there's other way to import the used .so in code,how can I fix this poblem?

**Comment by theFoxofSky** [comment]
Please check several things:
1.  Have you run 'python setup.py install' to build the '.so' files?
2. Have you move out the generated '.so' files from the 'build' folder?
3. Please check the path to 'grad_check.py', make sure it is outside the ddf folder.
